<a href="https://colab.research.google.com/github/CamilyVoltan/Ci-ncia_de_Dados_FATEC/blob/main/Atividade_P1_28_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Criando uma matriz 4x4
matriz = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

print("Matriz 4x4:")
print(matriz)
print()

# Elementos da diagonal principal
diagonal_principal = np.diag(matriz)
print("Elementos da diagonal principal:", diagonal_principal)

# Elementos da diagonal secundária
diagonal_secundaria = np.diag(np.fliplr(matriz))
print("Elementos da diagonal secundária:", diagonal_secundaria)

# Elementos em cima da diagonal do meio
acima_diagonal_principal = np.triu(matriz, k=1)
print("Elementos acima da diagonal principal:")
print(acima_diagonal_principal)

# Elementos debaixo da diagonal principal (do meio)
abaixo_diagonal_principal = np.tril(matriz, k=-1)
print("Elementos abaixo da diagonal principal:")
print(abaixo_diagonal_principal)

# Soma de todos os elementos da matriz
soma_total = np.sum(matriz)
print("Soma de todos os elementos da matriz:", soma_total)

# Soma de todos os elementos da 1ª coluna
soma_primeira_coluna = np.sum(matriz[:, 0])
print("Soma de todos os elementos da 1ª coluna:", soma_primeira_coluna)


Matriz 4x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Elementos da diagonal principal: [ 1  6 11 16]
Elementos da diagonal secundária: [ 4  7 10 13]
Elementos acima da diagonal principal:
[[ 0  2  3  4]
 [ 0  0  7  8]
 [ 0  0  0 12]
 [ 0  0  0  0]]
Elementos abaixo da diagonal principal:
[[ 0  0  0  0]
 [ 5  0  0  0]
 [ 9 10  0  0]
 [13 14 15  0]]
Soma de todos os elementos da matriz: 136
Soma de todos os elementos da 1ª coluna: 28
