**USANDO SHAPE**

**Sintaxe:** array.shape

In [ ]:
import numpy as np
a1 = np.array([])

**USANDO RESHAPE**

**Sintaxe:** array.reshape(lin, col)

In [ ]:
import numpy as np
vetor = np.arange(10) #vetor de 10 elementos #arange = para criar uma sequência númerica
print(f'Exibindo o vetor e {vetor.size} elementos: {vetor}')
print()

#Criando a matriz
#a quantidade de linhas x colunas deve ser igual a quantidade de elementos
matriz = vetor.reshape(5, 2)

print(f'Exiindo a matriz de {matriz.size} elemetntos: \n {matriz}')
print(f'Exibindo a forma da matriz: {matriz.shape}')

Exibindo o vetor e 10 elementos: [0 1 2 3 4 5 6 7 8 9]

Exiindo a matriz de 10 elemetntos: n [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Exibindo a forma da matriz: (5, 2)


**

In [ ]:
# reshape(numero de matriz, linhas, colunas)
# num_matrizes *linhas* colunas = quantidade de elementos
v = np.array(range(50)).reshape(2,5,5)

print('Shape = ', v.shape)
print('Número de dimensões = ', v.ndim) # v.ndim =
print('Número de elementos = ', v.dtype)
print('Matriz v = \n', v)

Shape =  (2, 5, 5)
Número de dimensões =  3
Número de elementos =  int64
Matriz v = 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


**USANDO RESIZE**

**Sintaxe:** array.resize

In [ ]:
import numpy as np
a = np.array([[0, 1], [2, 3]])
# como aumenta o tamanho
# ele faz uma cópia dos elementos
print(a)
b = np.resize(a,(2,5))
print(f'Matriz destino: \n {b}')

[[0 1]
 [2 3]]
Matriz destino: 
 [[0 1 2 3 0]
 [1 2 3 0 1]]


**OPERAÇÕES COM FUNÇÕES**

In [ ]:
import numpy as np

vetor = np.array([1, 2, 3])
print(f'Vetor original: {vetor}')

# calcular a raiz quadrada de todos os elementos do array
a



**MULTIPLICAÇÃO MATRICIAL**

In [ ]:
import numpy as np

a = np.array([[1, -2],[2, 4]])
b = np.array([[1, 2],[2, 4]])

mat = a.dot(b)
print(mat)

[[-3 -6]
 [10 20]]


In [ ]:
# Produto escalar e Produto vetorial entre vetores
import numpy as np

v1 = np.array([1, 1, 2])
v2 = np.array([-2, 2, 2])

prodEscalar = np.dot(v1, v2)
print(f'produto escalar: {prodEscalar}')

prodVetorial =

In [ ]:
# Multiplicação matricial entre matrizes

import numpy as np

A = np.array([[1, -2], [2, 4]])
B = np.array([[1, 2],[2, 4]])

print(f'Matriz A: {A}')
print(f'Matriz B: {B}')

print(f'\nMultiplicação AXB: {np.matmult(A, B)}')
print(f'\nMultiplicação')

In [ ]:
# Determinante de uma matriz e matriz inversa
import numpy as np

B = np.array([[2, 1],[5, 3]])

print(f'matriz B: \n {B}')
print(f'Determinante: {np.linalg.det(B):.2f}')
print(f'Inversa:\n {np.linalg.inv(B)}')

matriz B: 
 [[2 1]
 [5 3]]
Determinante: 1.00
Inversa:
 [[ 3. -1.]
 [-5.  2.]]
